import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import { notificationProvider, RefineSnackbarProvider } from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { ColorModeContextProvider } from "@contexts/color-mode";
import { dataProvider } from "@providers/data-provider";

export const metadata: Metadata = {
  title: "Limitless",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

const CustomTitle = () => (
  <div style={{ padding: "16px", fontWeight: "bold", fontSize: "20px" }}>
    Mi Sider Personalizado
  </div>
);


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";
console.log(dataProvider)
  return (
    <html lang="es">
      <body>
        <Suspense>

          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={notificationProvider}
                
                    resources={[
                      // {
                      //   name: "blog_posts",
                      //   list: "/blog-posts",
                      //   create: "/blog-posts/create",
                      //   edit: "/blog-posts/edit/:id",
                      //   show: "/blog-posts/show/:id",
                      //   meta: {
                      //     canDelete: true,
                      //   },
                      // },
                      // {
                      //   name: "categories",
                      //   list: "/categories",
                      //   create: "/categories/create",
                      //   edit: "/categories/edit/:id",
                      //   show: "/categories/show/:id",
                      //   meta: {
                      //     canDelete: true,
                      //   },
                      // },
                      {
                        name: "personas",
                        list: "/personas",
                        create: "/personas/create",
                        edit: "/personas/edit/:id",
                        show: "/personas/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "viviendas",
                        list: "/viviendas",
                        create: "/viviendas/create",
                        edit: "/viviendas/edit/:id",
                        show: "/viviendas/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "municipios",
                        list: "/municipios",
                        create: "/municipios/create",
                        edit: "/municipios/edit/:id",
                        show: "/municipios/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "qmfdZ5-skRLLz-JjtP04",
                      title: {
                     
                        text: "Limitless",
                      },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
